### ISSUE TITLE
Strange artifacts near 180ºE when reprojecting from EPSG:3857 to EPSG:4326 from level 5

### ISSUE THREAD

**Issue by SantiagoHorcajo** [mapproxy/mapproxy#286]
Hi there,

## Context
In one of our projects we need to expose the same service in two projections: EPSG:4326 and EPSG:3857. In our case, that implies to reproject a raster map service from EPSG:3857 to EPSG:4326.

## Actual Behavior
Strange artifacts are shown in raster images from level 5 near 180ºE. For example, level 4 is OK [4326level4](https://drive.google.com/file/d/0B3a135yKn4gDdkVILWdtMC1Ocm8/view?usp=sharing) and from level 5 is not OK [4326level5](https://drive.google.com/file/d/0B3a135yKn4gDRXoxNmFtWlJuYWc/view?usp=sharing). It seems like images are compressed from 180ºE to the left.

## Steps to Reproduce
You can see a live demo with this .yaml file
<pre>
services:
  demo:
  wmts:

layers:
  - name: Landsat4326
    title: Landsat4326
    sources: [cache_esri_world_landsat_4326]

caches:
  cache_esri_world_landsat_4326:
    grids: [geodetic]
    image:
      format: image/png
    sources: [cache_esri_world_landsat]
    disable_storage: true
    cache:
      type: sqlite

  cache_esri_world_landsat:
    grids: [webmercator]
    image:
      format: image/png
    sources: [src_esri_world_landsat]
    disable_storage: true
    cache:
      type: sqlite

sources:
  src_esri_world_landsat:
    type: tile
    url: http://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/%(z)s/%(y)s/%(x)s
    grid: webmercator
    transparent: true
    on_error:
      other:
        response: transparent
        cache: false

grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
  geodetic:
    base: GLOBAL_GEODETIC
    origin: nw    

globals:
</pre>
## Your Environment
* MapProxy 1.9.0
* Ubuntu 16.04

Thanks in advance,
Santiago Lastra

**Comment by olt** [comment]
This might be related to #285

**Comment by SantiagoHorcajo** [comment]
Anyway, will you treat this as a possible bug to test?

**Comment by olt** [comment]
Yes it is very likely bug. While the issue does affect you, it is an edge case and therefor the priority for this is lower, compared to other issues.

**Comment by malcolmrh** [comment]
Similar environment, similar context, and similar results. Seems like a pretty important 'edge case', since geodetic and webmercator maps are standard.

Here's an example going from EPSG 4326 to 3571:
![image](https://cloud.githubusercontent.com/assets/7484537/23231872/d3e5e87c-f8f5-11e6-8bae-07b15267f9d5.png)

**Comment by olt** [comment]
Can you upgrade to latest master and to Pillow 3.4 or higher? This might have been fixed already with some recent changes.

BTW: You should set `meta_size: [1, 1]` if you have a tile source with `disable_storage: true`.

**Comment by malcolmrh** [comment]
I tried Pillow 3.4.0 and MapProxy 1.9.1, and the issue wasn't solved for me. My issue may be slightly different, as it happens at all zoom levels when going from geodetic/webmercator/mercator to polar stereographic projections, and only for layers sourced from caches.

**Comment by olt** [comment]
Sorry, not 1.9.1 but the latest code from this repository.

    pip install https://github.com/mapproxy/mapproxy/tarball/master

See "Nightly" here https://mapproxy.org/download

**Comment by malcolmrh** [comment]
Thanks Oliver - but reprojecting to polar stereo (EPSG:3571, etc) still works for uncached, does not work for cached.

MapProxy==1.10.0a0.post20170224, Pillow==3.4.0

**Comment by olt** [comment]
@malcolmrh can you please create a new ticket for that with a working configuration and example URLs? I'd like to close this ticket when @SantiagoHorcajo confirms that this issue (EPSG:3857 to EPSG:4326) is fixed.

**Comment by SantiagoHorcajo** [comment]
Sorry but, for the moment, we can't upgrade our servers to "nightly" version to test if it's solved. For us is also a low priority bug and we have no plans to upgrade right now.
